# Homework 3  - Tryout pandas and numpy

Copy this notebook. Rename it as: YOURNAME-Homework-panda-numpy-Sept-2017

with your name replacing yourname and  replaced with the date you submit or to the last part.

Do the homeworks problems below.

Upload your completed jupyter notebook to your github site and send me the url via the elearning site as your homework submission. Please note that you need to do your own 3.4, and 3.5 if you share data and analysis from others then you cannot get more than a 3.  

## Homework 3.1

### 3.1.a
Load the data from: http://opendata.dc.gov/datasets that I have include in this github   
into a dataframe.  ( The file has been is available in directory ./data/ccp_current_csv.csv )

In [3]:
import pandas as pd
import numpy as np

hw = pd.read_csv("data/ccp_current_csv.csv")
hw

STREET QUADRANT            FROMINTERSECTION  \
0               13th St       NW                  Kennedy St   
1                  S St       NW            North Capitol St   
2      Rhode Island Ave       NE            Brentwood Rd (W)   
3               Mill Rd       NW                     27th St   
4      Rhode Island Ave       NE            Brentwood Rd (M)   
5             Mellon St       SE                      5th St   
6          Nebraska Ave       NW              Northampton St   
7           Military Rd       NW                     30th St   
8          Nebraska Ave       NW                   Oliver St   
9               16th St       NW                  Alaska Ave   
10         Shoemaker St       NW                 Linnean Ave   
11         Underwood St       NW             Piney Branch Rd   
12             Elder St       NW                      7th St   
13              26th St       NW              Northampton St   
14               4th St       NW              Madison St (N)   
15         Underwood Pl       NW            North Capitol St   
16              20th St       NW                 Columbia Rd   
17          Quintana Pl       NE                      3rd St   
18         Tuckerman St       NE                  Kansas Ave   
19              Eads St       NE                     45th St   
20               4th St       SE                  Newcomb St   
21              Belt Rd       NW                  Jenifer St   
22            Oneida St       NE           New Hampshire Ave   
23      Carrollsburg Pl       SW                        O St   
24              23rd St       NW          Washington Cir (N)   
25           Kanawha St       NW                    Utah Ave   
26      Piney Branch Rd       NW                Underwood St   
27              30th St       NW               Stephenson Pl   
28              32nd St       NW                 Woodland Dr   
29              33rd St       NW            Broad Branch Ter   
..                  ...      ...                         ...   
435      New Jersey Ave       NW                        F St   
436             15th St       NE                     Ames Pl   
437     East Capitol St       BN                        C St   
438         Randolph St       NE                     25th Pl   
439    South Dakota Ave       NE                Delafield St   
440          Wheeler Rd       SE                 Congress St   
441      New Jersey Ave       NW                        H St   
442     Mount Olivet Rd       NE               Brentwood Pky   
443              Oak St       NW                     16th St   
444        Michigan Ave       NE                     14th St   
445                C St       NE                     20th St   
446        Virginia Ave       SE                  6th St (S)   
447              Oak St       NW                Brown St (N)   
448         Florida Ave       NE                New York Ave   
449  North Carolina Ave       NE         East Capitol St (E)   
450            Elder St       NW                      8th St   
451          Benning Rd       SE                        G St   
452           School St       SW                      4th St   
453             18th St       NW                        M St   
454       Longfellow St       NW                     16th St   
455             10th St       NW                        M St   
456          Woodley Rd       NW             Connecticut Ave   
457          Woodley Rd       NW           Cathedral Ave (E)   
458              3rd St       SW            Independence Ave   
459             16th St       NW                 Primrose Rd   
460          Woodley Rd       NW                  Woodley Pl   
461         Western Ave       NW         Chevy Chase Cir (E)   
462             49th St       NW                   Fulton St   
463       Quackenbos St       NE           New Hampshire Ave   
464    North Capitol St       BN  Hawaii Ave  Rock Creek Chu   

                 TOINTERSECTION  NOOFBLOCKS     

### 3.1.a  what is its shape and what does that mean?

In [4]:
hw.shape
# This dataset has 465 rows and 27 columns.

(465, 27)

## Homework 3.2
 What are the number of rows in each 'QUADRANT' ?

In [5]:
pd.Series(hw.QUADRANT).value_counts()

NW    195
NE    163
SE     84
BN     12
SW     11
Name: QUADRANT, dtype: int64

## Homework 3.3 - Array math demonstration 
For two arrarys  

a= [1,2,3,4]  type=float

b= [5,6,7,8]  type=float

Peform the following array operations using numpy   
( show both operational use of numpy and functional (example addition operation => + vs addition function => numbpy.add() )

### 3.3.1 addition a+b 

In [17]:
%matplotlib inline
import matplotlib.pyplot as plt

from numpy import *

A = array([1,2,3,4], dtype = float)
B = array([5,6,7,8], dtype = float)
# use + operator
A + B 

array([ 6.,  8., 10., 12.])

In [18]:
# use add function
np.add(A,B)

array([ 6.,  8., 10., 12.])

### 3.3.2 subtraction a-b

In [19]:
# use - operator
A - B

array([-4., -4., -4., -4.])

In [21]:
# use subtract function
np.subtract(A,B)

array([-4., -4., -4., -4.])

### 3.3.3 multiplication a*b

In [22]:
# use * operator
A * B

array([ 5., 12., 21., 32.])

In [23]:
# use multiply function
np.multiply(A,B)

array([ 5., 12., 21., 32.])

### 3.3.4 divsion a/b

In [24]:
# use / operator
A / B

array([0.2       , 0.33333333, 0.42857143, 0.5       ])

In [25]:
# use divide function
np.divide(A,B)

array([0.2       , 0.33333333, 0.42857143, 0.5       ])

### 3.3.5 modulo  a%b

In [26]:
# use % operator
A % B

array([1., 2., 3., 4.])

In [27]:
# use fmod function
np.fmod(A,B)

array([1., 2., 3., 4.])

### 3.3.6 power  a^b

In [30]:
# use ** operator
A ** B

array([1.0000e+00, 6.4000e+01, 2.1870e+03, 6.5536e+04])

In [31]:
# use power function
np.power(A,B)

array([1.0000e+00, 6.4000e+01, 2.1870e+03, 6.5536e+04])

## Homework 3.4
Find your own data and load it into a dataframe

In [11]:
%matplotlib inline
import pandas as pd
import numpy as np

# Company executives from a large packaged foods manufacturer wished to determine which factors influence the market share of one of its products. Data were collected from a national database (Nielsen) for 36 consecutive months.
# market share : Average monthly market share for product (percent)
# price : Average monthly price of product (dollars)
# discount price : Presence or absence of discount price during, period: 1 if discount, 0 otherwise
# package promotion : Presence or absence of package promotion during, period: 1 if promotion present, 0 otherwise
mb = pd.read_excel('data/dataset.xlsx')
mb

identification number  market share  price  discount price  \
0                       1          3.15  2.198               1   
1                       2          2.52  2.186               0   
2                       3          2.64  2.293               0   
3                       4          2.55  2.420               1   
4                       5          2.69  2.179               1   
5                       6          3.02  2.207               1   
6                       7          2.52  2.127               1   
7                       8          2.45  2.206               1   
8                       9          2.42  2.305               0   
9                      10          3.16  2.260               0   
10                     11          2.60  2.205               0   
11                     12          2.98  2.340               0   
12                     13          2.50  2.171               0   
13                     14          2.45  2.201               1   
14                     15          3.06  2.248               1   
15                     16          2.34  2.184               1   
16                     17          2.88  2.373               0   
17                     18          2.94  2.157               0   
18                     19          2.72  2.129               1   
19                     20          2.33  2.557               0   
20                     21          2.64  2.587               1   
21                     22          2.76  2.255               1   
22                     23          3.05  2.124               0   
23                     24          2.48  2.683               0   
24                     25          2.23  2.336               0   
25                     26          2.65  2.266               1   
26                     27          2.56  2.443               1   
27                     28          2.66  2.478               1   
28                     29          2.99  2.394               0   
29                     30          2.30  2.414               0   
30                     31          2.88  2.233               1   
31                     32          2.80  2.302               0   
32                     33          2.48  2.421               1   
33                     34          2.85  2.518               0   
34                     35          3.16  2.497               1   
35                     36          3.05  2.781               1   

    package promotion month  year  
0                   0   Sep  1999  
1                   0   Oct  1999  
2                   0   Nov  1999  
3                   1   Dec  1999  
4                   1   Jan  1999  
5                   1   Feb  2000  
6                   1   Mar  2000  
7                   0   Apr  2000  
8                   1   May  2000  
9                   1   Jun  2000  
10                  1   Jul  2000  
11                  1   Aug  2000  
12                  0   Sep  2000  
13                  0   Oct  2000  
14                  0   Nov  2000  
15                  1   Dec  2001  
16                  0   Jan  2001  
17                  1   Feb  2001  
18                  0   Mar  2001  
19                  1   Jun  2001  
20                  0   Jul  2001  
21                  1   Aug  2001  
22                  1   Sep  2001  
23                  1   Oct  2001  
24                  0   Nov  2001  
25                  0   Dec  2001  
26                  0   Jan  2001  
27                  1   Feb  2001  
28                  1   Mar  2001  
29                  0   Apr  2002  
30                  0   May  2002  
31                  0   Jun  2002  
32                  0   Jul  2002  
33                  0   Aug  2002  
34                  1   Apr  2002  
35                  1   Jun  2002

## Homework 3.5
Provide an interesting analysis of the data columns ( frequency or averages )

In [13]:
# A useful summarization that gives a quick snapshot of multiple statistics for "price"
mb.price.describe()

count    36.000000
mean      2.324389
std       0.162982
min       2.124000
25%       2.200250
50%       2.279500
75%       2.420250
max       2.781000
Name: price, dtype: float64

In [17]:
# correlation between all columns
mb.corr()

identification number  market share     price  \
identification number               1.000000      0.080161  0.557243   
market share                        0.080161      1.000000 -0.027147   
price                               0.557243     -0.027147  1.000000   
discount price                      0.013390      0.073926 -0.035797   
package promotion                  -0.096262      0.202952  0.108551   
year                                0.949841      0.050125  0.467311   

                       discount price  package promotion      year  
identification number        0.013390          -0.096262  0.949841  
market share                 0.073926           0.202952  0.050125  
price                       -0.035797           0.108551  0.467311  
discount price               1.000000          -0.055641 -0.008158  
package promotion           -0.055641           1.000000 -0.087969  
year                        -0.008158          -0.087969  1.000000

In [19]:
# mean of each columns
mb.mean()

identification number      18.500000
market share                2.707222
price                       2.324389
discount price              0.527778
package promotion           0.500000
year                     2000.638889
dtype: float64

In [22]:
# sum of each columns
mb.sum()

identification number                                                  666
market share                                                         97.46
price                                                               83.678
discount price                                                          19
package promotion                                                       18
month                    SepOctNovDecJanFebMarAprMayJunJulAugSepOctNovD...
year                                                                 72023
dtype: object

In [30]:
# count how many rows in each month
pd.Series(mb.month).value_counts()

Jun    4
Jul    3
Oct    3
Dec    3
Nov    3
Apr    3
Sep    3
Aug    3
Feb    3
Mar    3
Jan    3
May    2
Name: month, dtype: int64

In [31]:
# count how many rows in each year
pd.Series(mb.year).value_counts()

2001    14
2000    10
2002     7
1999     5
Name: year, dtype: int64

In [44]:
# the most difference between all the price
mb1 = mb[['price']]
price_range = lambda price: mb.price.max() - mb.price.min()
mb1.apply(price_range)

price    0.657
dtype: float64